config/routes.rb
Rails.application.routes.draw do
  root "challenges#index"
  # post "challenge/create"
  devise_for :users
  resources :challenges do
    resource :collaborator, only: [:create, :destroy]
    resource :vote, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/challenge.rb
class Challenge < ApplicationRecord
  belongs_to :user
  validates :title, :description, presence: true
  has_many :votes, dependent: :destroy
  has_many :collaborate, dependent: :destroy
  has_many :tags, dependent: :destroy
  self.per_page = 5

  def voted_by?(user)
    votes.exists?(user: user)
  end

  def collaborated_by?(user)
    collaborate.exists?(user: user)
  end

  def collaboraters_name(challenge_id)
    name_string = []
    user_id = Collaborate.select(:user_id).where(challenge_id: challenge_id)
    user_id.each do |user|
      name_string << User.find(user.user_id).empid
    end
    return(name_string)
  end
end

app/models/collaborate.rb
class Collaborate < ApplicationRecord
  belongs_to :user
  belongs_to :challenge
end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :challenge
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :challenges, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :collaborate, dependent: :destroy
  validates :empid, presence: true, uniqueness: { case_sensitive: false }
  attr_writer :login
  validates_format_of :empid, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true

  def login
    @login || self.empid || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["empid = :value OR lower(email) = lower(:value)", { :value => login }]).first
    elsif conditions.has_key?(:empid) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :challenge
end

app/controllers/application_controller.rb
require "will_paginate/array"

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:empid, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/challenge_controller.rb
class ChallengeController < ApplicationController
  # before_action :authenticate_user!

  def index
    if params[:sort] == "most_votes"
      @challenges = Challenge.all.sort_by { |challenge| challenge.votes.count }.reverse
    elsif params[:sort] == "least_votes"
      @challenges = Challenge.all.sort_by { |challenge| challenge.votes.count }
    elsif params[:title_search]
      @challenges = Challenge.where("title LIKE ?", "%#{params[:title_search]}%")
    elsif params[:employee_search]
      @challenges = Challenge.where("user_id LIKE ?", "%#{params[:employee_search]}%")
    else
      @challenges = Challenge.order(params[:sort])
    end
    @challenge = Challenge.new(user: current_user)
    # @challenge.user = current_user
  end

  def create
    # @challenge = current_user.challenges.build(title: params[:challenge][:title], description: params[:challenge][:description])
    @challenge = Challenge.new(title: params[:challenge][:title], description: params[:challenge][:description])
    @challenge.user = current_user
    if @challenge.save
      tag_string = params[:challenge][:tags]
      tag_array = tag_string.split(",")
      tag_array.each do |tag_name|
        @challenge.tags.create(name: tag_name)
      end
      redirect_to root_path, notice: "challenge created"
    else
      redirect_to root_path, alert: "Error: challenge not saved"
    end
  end

  private

  def set_params
    params.require(:challenge).permit(:title, :description, :tags, :user_id)
  end
end

app/controllers/challenges_controller.rb
class ChallengesController < ApplicationController
  # include ChallengeService
  before_action :authenticate_user!, only: [:create, :destroy]

  def index
    @challenges = ChallengeSortSearch.new(params).call
    @challenge = Challenge.new(user: current_user)
  end

  def create
    @challenge = ChallengeCreate.new(set_params.merge(user: current_user).except(:tags)).call
    if @challenge.save
      @tag = ChallengeTag.new(@challenge.id, params[:challenge][:tags]).call
      redirect_to root_path, notice: "Challenge Created"
    else
      redirect_to root_path, alert: "Error: Challenge Not Saved"
    end
  end

  def show
    @challenge = Challenge.find(params[:id])
  end

  def destroy
    @challenge = Challenge.find(params[:id])
    @challenge.destroy
    redirect_to root_path, notice: "Challenge Deleted"
  end

  private

  def set_params
    params.require(:challenge).permit(:title, :description, :user_id, :tags)
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :authenticate_user!

  def create
    challenge = Challenge.find(params[:challenge_id])
    challenge.collaborate.create(user: current_user)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    challenge = Challenge.find(params[:challenge_id])
    challenge.collaborate.where(user: current_user).take.try(:destroy)
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :authenticate_user!

  def create
    @challenge = Challenge.find(params[:challenge_id])
    @challenge.votes.create(user: current_user)
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @challenge = Challenge.find(params[:challenge_id])
    # @challenge.votes.where(user: current_user).take.try(:destroy)
    # debugger
    Vote.find_by(user: current_user, challenge: @challenge).destroy

    redirect_back(fallback_location: root_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/challenge_helper.rb
module ChallengeHelper
end

app/helpers/collaborate_helper.rb
module CollaborateHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/challenge/index.html.erb
<%= form_for @challenge, class: "form-inline ", :url => { :action => "create" } do |f| %>
<div class= "form-field">
    <%= f.text_field :title, placeholder: "Title", class: "form-control " %>
    <%= f.text_field :description, placeholder: "Description", class: "form-control" %>
    <%= f.text_field :tags, value: "", placeholder: "Tags", class: "form-control" %>
  </div>
    <%= f.text_field :user_id, :type => "hidden" %>
    <%= f.submit "Add Challenge", class: "btn btn-outline-info" %>
<% end %>
<div class ="features">
  <div class="dropdown">
    <form>
    <a class="btn btn-secondary dropdown-toggle" role="button"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Sort
    </a>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
      <div><%= link_to "Recent challenge", :sort => "created_at ASC" %></div>
      <div> <%= link_to "older challenge", :sort => "created_at DESC" %></div>
      <div> <%= link_to "Most Votes", :sort => "most_votes" %></div>
      <div> <%= link_to "least Votes", :sort => "least_votes" %></div>
    </div> 
    </form>
  </div>
  <div>
    <form class="form-inline my-2 my-lg-0 mr-auto" action="<%= challenge_index_path %>">
          <input class="form-control mr-sm-2 search" type="Text" placeholder="Filter by title" aria-label="Search" name="title_search" >
          <button class="btn my-2 my-sm-0" type="submit"></button>
    </form>
  </div>
  <div>
    <form class="form-inline my-2 my-lg-0 mr-auto" action="<%= challenge_index_path %>">
          <input class="form-control mr-sm-2 search" type="Text" placeholder="Filter by emp id" aria-label="Search" name="employee_search" >
          <button class="btn my-2 my-sm-0" type="submit"></button>
    </form>
  
  </div>
</div>

<table class="table  table-bordered">
  <thead class="thead">
    <tr>
      <th scope="col">Challenge Id</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Tags</th>
      <th scope="col">Vote Count</th>
      <th scope="col">Created by</th>
      <th scope="col">Created at</th>
      <th scope="col">Vote</th>
      <th scope="col">Collaborate</th>
      <th scope="col">Collaborators</th>
    </tr>
  </thead>
  <tbody>
  <% @challenges.each do |challenge| %> 
    <tr>
      <td><%= challenge.id %></td>
      <td><%= challenge.title %></td>
      <td><%= challenge.description %></td>
      <td>
      <% challenge.tags.each do |tag| %>
       <%= "#{tag.name}," %>
      <% end %>
      </td>
      <td><%= challenge.votes.count %></td>
      <td><span><%= challenge.user.empid %></span></td>
      <td><%= challenge.created_at %></td>
      <% if challenge.user != current_user %>
          <td>
          <% if challenge.voted_by? current_user %>
           <%= link_to "<svg xmlns='http://www.w3.org/2000/svg' width='22' height='22' fill='currentColor' class='bi bi-x' viewBox='0 0 16 16'>
                                        <path d='M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z'/>
                                       </svg>".html_safe, challenge_vote_path(challenge), method: :delete %>
          <% else %>
            <%= link_to "<svg xmlns='http://www.w3.org/2000/svg' width='22' height='22' fill='currentColor' class='bi bi-plus' viewBox='0 0 16 16'>
                                        <path d='M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z'/>
                                       </svg>".html_safe, challenge_vote_path(challenge), method: :post %>
          <% end %>
          </td>
          <td>
          <% if challenge.collaborated_by? current_user %>
             <%= link_to "<svg xmlns='http://www.w3.org/2000/svg' width='22' height='22' fill='currentColor' class='bi bi-x' viewBox='0 0 16 16'>
                                          <path d='M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z'/>
                                         </svg>".html_safe, challenge_collaborator_path(challenge), method: :delete %>
          <% else %>
            <%= link_to "<svg xmlns='http://www.w3.org/2000/svg' width='22' height='22' fill='currentColor' class='bi bi-check' viewBox='0 0 16 16'>
                                        <path d='M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z'/>
                                      </svg>".html_safe, challenge_collaborator_path(challenge), method: :post %> 
        <% end %> 
        </td>
        <% else %>
          <td></td>
          <td></td>
      <% end %>
      <td>
        <% challenge.collaboraters_name(challenge.id).each do |name| %>
          <%= "#{name}," %>
        <% end %>
      </td>
    </tr>
  <% end %> 
  </tbody>
</table>

app/views/challenges/index.html.erb
<%= form_for @challenge, class: "form-inline ", :url => { :action => "create" } do |f| %>
<div class= "form-field">
    <%= f.text_field :title, placeholder: "Title", class: "form-control " %>
    <%= f.text_field :description, placeholder: "Description", class: "form-control" %>
    <%= f.text_field :tags, value: "", placeholder: "Enter comma seperated Tags", class: "form-control" %>
  </div>
    <%= f.text_field :user_id, :type => "hidden" %>
    <%= f.submit "Add Challenge", class: "btn btn-outline-info" %>
<% end %>
<div class ="features">
  <div class="dropdown">
    <form>
    <a class="btn btn-secondary dropdown-toggle" role="button"  data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Sort
    </a>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
      <div><%= link_to "Recent challenge", :sort => "created_at ASC" %></div>
      <div> <%= link_to "older challenge", :sort => "created_at DESC" %></div>
      <div> <%= link_to "Most Votes", :sort => "most_votes" %></div>
      <div> <%= link_to "least Votes", :sort => "least_votes" %></div>
    </div> 
    </form>
  </div>
  <div>
    <form class="form-inline my-2 my-lg-0 mr-auto" action="<%= challenges_path %>">
          <input class="form-control mr-sm-2 search" type="Text" placeholder="Filter by title" aria-label="Search" name="title_search" >
          <button class="btn my-2 my-sm-0" type="submit"></button>
    </form>
  </div>
  <div>
    <form class="form-inline my-2 my-lg-0 mr-auto" action="<%= challenges_path %>">
          <input class="form-control mr-sm-2 search" type="Text" placeholder="Filter by emp id" aria-label="Search" name="employee_search" >
          <button class="btn my-2 my-sm-0" type="submit"></button>
    </form>
  
  </div>
</div>

<table class="table  table-bordered">
  <thead class="thead">
    <tr>
      <th scope="col">Challenge Id</th>
      <th scope="col">Title</th>
      <th scope="col">Description</th>
      <th scope="col">Tags</th>
      <th scope="col">Vote Count</th>
      <th scope="col">Created by</th>
      <th scope="col">Created at</th>
      <th scope="col">Vote</th>
      <th scope="col">Collaborate</th>
      <th scope="col">Collaborators</th>
      <th scope="col">Delete Challenge</th>
    </tr>
  </thead>
  <tbody>
  <% @challenges.each do |challenge| %> 
    <tr>
      <td><%= challenge.id %></td>
      <td><%= challenge.title %></td>
      <td><%= challenge.description %></td>
      <td>
      <% challenge.tags.each do |tag| %>
       <%= "#{tag.name}," %>
      <% end %>
      </td>
      <td><%= challenge.votes.count %></td>
      <td><span><%= challenge.user.empid %></span></td>
      <td><%= challenge.created_at %></td>
      <% if challenge.user != current_user %>
          <td>
          <% if challenge.voted_by? current_user %>
           <%= link_to "<svg xmlns='http://www.w3.org/2000/svg' width='22' height='22' fill='currentColor' class='bi bi-x' viewBox='0 0 16 16'><path d='M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z'/></svg>".html_safe, challenge_vote_path(challenge), method: :delete %>
          <% else %>
            <%= link_to "<svg xmlns='http://www.w3.org/2000/svg' width='22' height='22' fill='currentColor' class='bi bi-plus' viewBox='0 0 16 16'><path d='M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z'/></svg>".html_safe, challenge_vote_path(challenge), method: :post %>
          <% end %>
          </td>
          <td>
          <% if challenge.collaborated_by? current_user %>
             <%= link_to "<svg xmlns='http://www.w3.org/2000/svg' width='22' height='22' fill='currentColor' class='bi bi-x' viewBox='0 0 16 16'><path d='M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z'/></svg>".html_safe, challenge_collaborator_path(challenge), method: :delete %>
          <% else %>
            <%= link_to "<svg xmlns='http://www.w3.org/2000/svg' width='22' height='22' fill='currentColor' class='bi bi-check' viewBox='0 0 16 16'><path d='M10.97 4.97a.75.75 0 0 1 1.07 1.05l-3.99 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.267.267 0 0 1 .02-.022z'/></svg>".html_safe, challenge_collaborator_path(challenge), method: :post %> 
        <% end %> 
        </td>
        <% else %>
          <td></td>
          <td></td>
      <% end %>
      <td>
        <% challenge.collaboraters_name(challenge.id).each do |name| %>
          <%= "#{name}," %>
        <% end %>
      </td>
      <% if challenge.user == current_user %>
        <td>
          <%= link_to "Delete", challenge, method: :delete, data: { confirm: "Are you sure" } %>
        </td>
      <% else %>
        <td></td>
      <% end %>
    </tr>
  <% end %> 
  </tbody>
</table>
<%= will_paginate @challenges, :renderer => WillPaginate::ActionView::Bootstrap4LinkRenderer %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackathon</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track': "reload" %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
  </head>
  <body>
    <div class="header">
      <%= link_to "Home", root_path, class: "home txt" %>
      <div class="hackathon txt">Hackathon</div>
      <div>
      <% if current_user %>
      <%= link_to "sign out", destroy_user_session_path, method: :delete %>
      <%= current_user.empid %>
    <% else %>  
      <%= link_to "sign in", new_user_session_path %>
      <% link_to "sign up", new_user_registration_path %>
    <% end %>
    </div>
   </div> 
  <div class="container-fluid">
    <%= yield %>
    <% if notice == nil && alert != nil || notice != nil && alert == nil %>
      <div class="notice-alert", id="notice-alert">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <script type="text/javascript">
        setTimeout(function(){
          hideFlashMessage()
        }, 3000)

      </script>
      </div>
    <% end %>
  </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

  </body>
</html>